# Generated by Django 4.0.6 on 2022-07-29 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=2000)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=100)),
                ('data', models.DateTimeField(default=datetime.datetime(2022, 7, 29, 8, 59, 20, 609483))),
            ],
        ),
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=2000)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=100)),
                ('data', models.DateTimeField(default=datetime.datetime(2022, 7, 29, 8, 59, 20, 609246))),
            ],
        ),
    ]
