# Generated by Django 4.0.6 on 2022-07-29 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevenueExpenseControl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 9, 8, 33, 484785)),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 9, 8, 33, 484528)),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
