# Generated by Django 4.0.6 on 2022-07-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevenueExpenseControl', '0002_alter_despesas_data_alter_despesas_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
