# Generated by Django 4.0.6 on 2022-07-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevenueExpenseControl', '0003_alter_despesas_data_alter_receitas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='data',
            field=models.DateField(),
        ),
    ]
