# Generated by Django 4.0.6 on 2022-07-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RevenueExpenseControl', '0004_alter_despesas_data_alter_receitas_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Despesas',
            new_name='Despesa',
        ),
        migrations.RenameModel(
            old_name='Receitas',
            new_name='Receita',
        ),
    ]
